[package]
name = "cerberus-daemon"
version = "0.1.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

libc = "0.2"
