[workspace]
members = [
  "crates/cerberus-store",
  "crates/cerberus-tauri",
]
resolver = "2"

[workspace.dependencies]
thiserror = "1.0"
anyhow = "1.0"

cerberus-store = { path = "crates/cerberus-store" }
