[package]
name = "cerberus-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"

serde.workspace = true
zeroize.workspace = true
cerberus-secret.workspace = true

[dev-dependencies]
serde_json.workspace = true
