[package]
name = "cerberus-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"

[dev-dependencies]
cerberus-crypto.workspace = true
hmac.workspace = true
serde_json.workspace = true
